"""Reproduce the consolidated proposal; historical inputs remain unchanged."""
import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent


def section(text, start, end):
    if text.count(start) != 1 or text.count(end) != 1:
        raise ValueError('ambiguous section boundary')
    return text.split(start, 1)[1].split(end, 1)[0].strip()


def replace_once(text, old, new):
    if text.count(old) != 1:
        raise ValueError('consolidation input changed')
    return text.replace(old, new, 1)


def render():
    manifest = json.loads((ROOT / 'consolidated-inputs.json').read_text())
    if (manifest.get('kind') != 'consolidated-proposal-inputs' or
            manifest.get('revision') != 'bf854ac321bd1569f04553f64663470093097da3' or
            manifest.get('status') != 'PROPOSAL_NOT_ADOPTED' or
            set(manifest.get('files', {})) != {'README.md', 'owner-contract.md', 'addendum.md', 'resolutions.md'}):
        raise ValueError('input provenance mismatch')
    texts = {}
    for name, digest in manifest['files'].items():
        raw = (ROOT / name).read_bytes()
        if hashlib.sha256(raw).hexdigest() != digest:
            raise ValueError('input hash mismatch: ' + name)
        texts[name] = raw.decode()
    base = section(texts['README.md'], '## Scope and compatibility', '## Review disposition')
    base = replace_once(base,
        'For this binding each decrypted control message is at most **16,348 bytes**, the\ncurrent core carriage ceiling, not the larger general session maximum. Wire messages\nare at most **32,768 bytes**.',
        'Every control or protected message has at most **16,348 plaintext bytes**,\n**16,384 record bytes** and **32,768 wire-envelope bytes**, before and after READY.\nThe complete-message rules below define counting and failure handling.')
    base = replace_once(base, 'Immediately before publishing every transition, including after validation, gate',
                        'Immediately before publishing every SETUP transition, including after validation, gate')
    owner = section(texts['owner-contract.md'], '## Ownership and trusted dependencies', '## Evidence required before implementation claims')
    owner = replace_once(owner,
        'At or after the\n   setup deadline, or after close/invalidation, discard the completion and close.',
        'Use the operation-class deadline defined below: SETUP retains its original\n   setup deadline; PROTECTED uses its fixed request/I/O deadline. At or after\n   that applicable deadline, or after close/invalidation, discard completion and close.')
    owner = replace_once(owner,
        'A completion observed before the deadline\nbut published at the deadline fails.',
        'A SETUP completion observed before its deadline\nbut published at that deadline fails. PROTECTED completion uses its own deadline.')
    start = 'Closure before the protected handoff wins and prevents admission.'
    end = 'ordering with close and current authority checks using the actual Guard API.'
    obsolete = start + owner.split(start, 1)[1].split(end, 1)[0] + end
    owner = replace_once(owner, obsolete,
        'Handoff and reservation are not final admission. The final dispatch admission\nrules below define one shared ordering with owner closure; implementations must\nnot substitute an earlier handoff for that event.')
    limits = section(texts['addendum.md'], '## Proposed complete-message limits', '## Proposed owner verification coverage')
    resolution = texts['resolutions.md']
    final = section(resolution, '## DREV-01: Final dispatch admission orders with closure', '## DREV-02: Separate setup and protected-operation deadlines').split('\nRe-review:', 1)[0]
    deadline = section(resolution, '## DREV-02: Separate setup and protected-operation deadlines', '## DREV-03: Explicit Ed25519 signature subset').split('\nRe-review:', 1)[0]
    algorithms = section(resolution, '## DREV-03: Explicit Ed25519 signature subset', '## Evidence and adoption state').split('\nRe-review:', 1)[0]
    return '\n\n'.join([
        '# Consolidated SAGE authenticated non-HTTP MCP binding draft',
        'Status: **PROPOSAL_NOT_ADOPTED**; SAGE **0.10.0**, MCP **2025-06-18**.\n'
        'This is the single integrated reading of the proposed behavior, not an adopted\n'
        'normative release. MUST/SHOULD apply conditionally on future adoption. Historical\n'
        'proposals and reviews retain their original scope and are not alternative rule\n'
        'choices for this draft. It does not replace the unpublished local baseline.',
        'Generated by `python3 -B consolidate.py --write` from the exact source hashes in\n'
        '[consolidated-inputs.json](consolidated-inputs.json). Use `--check` to detect drift.\n'
        'The transformations expand size scope, select operation-specific deadlines and\n'
        'replace the ambiguous handoff paragraph with final admission rules. This is\n'
        'text integration, not a new independent security review or implementation.',
        '## Scope and compatibility\n\n' + base,
        '## Complete-message limits\n\n' + limits,
        '## Ownership and trusted dependencies\n\n' + owner,
        '## Final dispatch admission and closure\n\n' + final,
        '## Operation deadline classes\n\n' + deadline,
        '## Signature algorithm compatibility\n\n' + algorithms,
        '## Evidence and adoption status\n\n'
        'The [original plan](cases.json), [addendum plan](addendum-cases.json) and\n'
        '[resolution plan](resolutions.json) contain 40 + 18 + 13 = **71 NOT_RUN**\n'
        'protocol cases. The historical lifecycle remains **37 NOT_RUN** and conformance\n'
        '**NOT_ESTABLISHED**. Earlier 40/58-case reports remain historical, not total\n'
        'coverage of this integrated draft. The original Inspector model covers selected\n'
        'setup ordering only, not final admission or protected output deadlines.\n\n'
        'External independent review remains NOT_PERFORMED. The three findings in\n'
        '[the design review](design-review.md) are resolved in the proposed text only,\n'
        'as recorded by the same author in [resolutions](resolutions.md). Next: review\n'
        'this single draft, reconcile the unpublished normative baseline and traceability,\n'
        'and explicitly adopt before core API and actual protocol execution claims.\n'
        'HTTP mapping, generic MCP interoperability and host-wide protection remain outside\n'
        'this binding. No new wire field or portable readiness credential is introduced.'
    ]) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--write', action='store_true')
    args = parser.parse_args()
    try:
        result = render()
        output = ROOT / 'consolidated.md'
        if args.write:
            output.write_text(result)
        elif output.read_text() != result:
            raise ValueError('consolidated document differs from pinned integration')
    except (ValueError, KeyError, OSError) as error:
        print(f'Consolidation FAIL: {error}', file=sys.stderr)
        sys.exit(1)
    print('Consolidation PASS: exact text integration only; 71 protocol cases NOT_RUN.')
